### ISSUE TITLE
 'date' header stripped for fetch request?

### ISSUE THREAD

**Issue by drone1** [jessety/simple-hmac-auth#7]
Hi. I'm using Chrome Version 87.0.4280.88 (Official Build) (x86_64) and simple-hmac-auth v3.3.1.

For the pre-flight request, my server returns the following response headers (note 'date' included here in ``access-control-allow-headers``):

```access-control-allow-credentials: true
access-control-allow-headers: authorization,content-type,signature,date
access-control-allow-methods: GET,HEAD,OPTIONS,POST,PUT
access-control-allow-origin: http://www.myfakedevhost.com:3000
connection: keep-alive
date: Thu, 31 Dec 2020 03:41:51 GMT
transfer-encoding: chunked
```

Then, oddly,``date`` isn't included as part of the actual request headers, despite the fact that I've stepped through the code and see that date is explicitly being added as a header to the request. 

simple-hmac-auth seems to be doing its job, setting the date header and making the HTTP request as expected, however either the ``http`` library or Chrome is stripping it.

Any thoughts on what gives here? Is Chrome filtering it out for some reason (some CORS misunderstanding I might be having)?

Additional data below. Thanks for any help.

```
			const authClient = new SimpleHMACAuth.Client(
				user.webApiKey(),
				user.webApiSecret(), {
				  host: 'myfakedevhost.com',
				  port: 3000,
				  ssl: false,
				  verbose: true,
				}
			) 
			const options = { method: 'GET', path: '/some/api', query: null, data: { q: 1 } }
			authClient.request(options, (error, result) => onProcessResult(error, result))
```

**Comment by drone1** [comment]
Whoops, didn't mean to close the issue!

Basically, the issue boils down to the 'date' header properly being set, as far as I can tell, and a request made (using HTTP, not SSL), but Chrome does not actually send the date header – it's conspicuously missing from the request headers in Network tab:

```
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,de;q=0.8,es;q=0.7
authorization: api-key <key>
Cache-Control: no-cache
Connection: keep-alive
content-type: application/json
Host: myfakedevhost.com:3000
Origin: http://www.myfakedevhost.com:3000
Pragma: no-cache
Referer: http://www.myfakedevhost.com:3000/
signature: simple-hmac-auth sha256 <signature>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
```

Note that authorization, signature and content-type are there just fine, but date isn't, even though it comes back from the pre-flight request in ``access-control-allow-headers``. 

```
access-control-allow-credentials: true
access-control-allow-headers: authorization,content-type,signature,date
access-control-allow-methods: GET,HEAD,OPTIONS,POST,PUT
access-control-allow-origin: http://www.myfakedevhost.com:3000
connection: keep-alive
date: Thu, 31 Dec 2020 15:20:43 GMT
transfer-encoding: chunked
```

Yet on the line that makes the HTTP request, options.headers.date is properly set: https://github.com/jessety/simple-hmac-auth/blob/37b432624256c0d550f735a3c16c5d38bbd2d554/src/Client.js#L349

Here is the value of 'options' at this line:

```
agent: http.Agent {}
data: {x: "{"y":"blahblah"}"}
headers: {authorization: "api-key <api-key>", date: "Thu, 31 Dec 2020 15:12:50 GMT", content-type: "application/json", content-length: 42, signature: "simple-hmac-auth sha256 <signature>"}
host: "myfakedevhost.com"
method: "GET"
path: "/some/api"
port: 3000
query: null
```

Any thoughts on what I am missing? Something related to the fact that I've got an edited /etc/hosts w/ 
```
127.0.0.1 myfakedevhost.com
127.0.0.1 www.myfakedevhost.com
```

I can't test easily w/o the fake dev host but may have to try to figure that out.

FWIW, for the pre-flight response, I'm sending 'date' back with the other allowed headers w/ the code below. Note that I've tried setting 'Access-Control-Allow-Origin' to '*' for the hell of it but Chrome still won't send the date header.

```
	res.setHeader('Access-Control-Allow-Origin', "http://www.myfakedevhost.com:3000")
	res.setHeader('Access-Control-Allow-Credentials', 'true')
	res.setHeader('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS,POST,PUT')

	// Deal with pre-flight request, which checks which headers are OK to send for the
	// actual, forthcoming request.
	// See https://stackoverflow.com/questions/32500073/request-header-field-access-control-allow-headers-is-not-allowed-by-itself-in-pr
	if (req.method == 'OPTIONS' && 'access-control-request-headers' in req.headers) {
		const controlAllowHeaders = `${req.headers['access-control-request-headers']},date`	// Add 'date' since it's required for the actual request
		res.setHeader('Access-Control-Allow-Headers', controlAllowHeaders)
		res.writeHead(200, {})
		res.end()
		return
	}
```

The headers for the pre-flight request look fine in Chrome: ``access-control-allow-headers: authorization,content-type,signature,date`` as expected.

I've even added a new custom header to the pre-flight response and to simple-hmac-auth, and it's also stripped from the fetch request.

**Comment by drone1** [comment]
OK, I'm at a total loss as to how setting the 'date' header has worked for anyone since it's listed in the forbidden header names (https://fetch.spec.whatwg.org/#forbidden-header-name) which are only set by the user agent & cannot be set by JS code, which is what this package does. Can someone please help me understand this? Thanks.

If I modify the code to set & read a 'test' header instead, I'm able to move beyond the timestamp error.

**Comment by drone1** [comment]
I forked and got this working ages ago, by the way. Should I create a pull request? I see you're still setting the ``date`` header...

https://github.com/jessety/simple-hmac-auth/blob/b3a99efee632ac623544dc99d1c4c12cd640db3a/src/Client.ts#L249

**Comment by jessety** [comment]
Hi @drone1! First of all, apologies for the very long wait on this.

Web browsers were not the use case I was targeting when designing the protocol. I've used it for a few years to communicate from either iOS apps (via [simple-hmac-auth-swift](https://github.com/jessety/simple-hmac-auth-swift)) or to communicate between backend services across untrusted network conditions. This way, the `secret` key never has to be transmitted across the network before being used to authenticate the client- whereas in a browser it will always have to be.

That said, I'm all for it. I haven't personally tried using it in web browser but if this is the only impediment I don't see a reason not to shift over to it. I just kicked off a PR that will support both `date` and `timestamp` in the backend, defaulting to `timestamp` unless otherwise specified. I'll add a few more tests and if all looks well, I'll publish this as a semver major update since it introduced breaking default behavior: https://github.com/jessety/simple-hmac-auth/pull/12

**Comment by jessety** [comment]
`simple-hmac-auth` v4.0.0 is now live. The client library now uses the `timestamp` header by default, but the server class supports both `date` and `timestamp` so it's fully backwards compatible.
I also updated the [express](https://github.com/jessety/simple-hmac-auth-express) and [koa](https://github.com/jessety/simple-hmac-auth-koa) middleware libraries to `v4.0.0`, so servers that use either will fully support clients that send `timestamp` now.

Like I said earlier, I haven't tested this in a web browser so I'm not sure how well it will work there, but I hope this is an improvement!
